name: Latest Blog Post Workflow

on:
  schedule:
    # 매일 오후 12시에 실행
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 5
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
          feed_list: "https://your-blog-url.com/feed.xml"
          template: "$newline- [$title]($url) $newline"
          commit_message: "Updated with the latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }} 