name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: kimmaru
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul

      - name: Base metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimmaru
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Seoul

      - name: Plugin stars
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimmaru
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Plugin isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimmaru
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Plugin habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimmaru
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Seoul

      - name: Plugin languages details
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: kimmaru
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_details: 2
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8 