name: Spotify Now Playing

on:
  schedule:
    # 매 5분마다 실행
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-spotify:
    name: Update Spotify Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Spotify Playing Now
        uses: kittinan/spotify-github-profile@v1
        with:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          commit_message: "🎵 Updated Spotify status" 